baseurl = "http://blog.rmenn.in"
languageCode = "en"
title = "rmenn - personal blog"
theme = "hemingway"
copyright = "&copy; <a href=\"https://github.com/rmenn\">Rahul Menon</a> 2018"
disqusShortname = ""
googleAnalytics = "UA-84739535-1"

[params]

[params.highlight]
style = "github"
languages = ["go", "containers"]

[[params.social]]
url = "https://github.com/rmenn"
fa_icon = "fa-github"

[[params.social]]
url = "https://twitter.com/rmenn"
fa_icon = "fa-twitter"

[[params.social]]
url = "/index.xml"
fa_icon = "fa-rss"
